# Generated by Django 5.0.1 on 2025-05-15 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('FILE_SUBMISSION', 'File Submission')], default='FILE_SUBMISSION', max_length=50),
        ),
        migrations.CreateModel(
            name='FileSubmissionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_file_types', models.JSONField(default=list, help_text="List of allowed file extensions (e.g., ['pdf', 'doc', 'docx'])")),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size in megabytes')),
                ('submission_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_submission', to='courses.assessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
