# Generated by Django 5.0.1 on 2025-05-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_filesubmission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesubmission',
            unique_together=set(),
        ),
    ]
