# Generated by Django 5.0.1 on 2025-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('corporate', 'Corporate')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
