# Generated by Django 5.0.1 on 2025-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_theme_user_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('corporate', 'Corporate'), ('modern', 'Modern'), ('ocean', 'Ocean'), ('sunset', 'Sunset')], default='default', max_length=20),
        ),
    ]
