# Generated by Django 5.0.1 on 2025-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organization_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('corporate', 'Corporate')], default='default', max_length=20),
        ),
    ]
